import data from './environment.json'

const FACEANALYCER_KEY = data.VITE_FACEANALYCER_API_KEY;
const FACEANALYCER_HOST = data.VITE_FACEANALYCER_API_HOST;

export const FACEANALYCER = { FACEANALYCER_KEY: FACEANALYCER_KEY, FACEANALYCER_HOST: FACEANALYCER_HOST };

const OPENWEATHER_KEY = data.VITE_OPENWEATHER_API_KEY;
const OPENWEATHER_HOST = data.VITE_OPENWEATHER_API_KEY;

export const OPENWEATHER = { OPENWEATHER_KEY: OPENWEATHER_KEY, OPENWEATHER_HOST: OPENWEATHER_HOST };